import logging
import time
import os

class JulesAgent:
    def __init__(self, browser_agent, llm_client=None):
        self.browser = browser_agent
        self.llm = llm_client # Fallback API

    def submit_task_to_jules(self, repo_name, instructions):
        logging.info(f"Connecting to jules.google.com for repo {repo_name}...")
        try:
            page = self.browser.page
            # 1. Navigate to Jules
            self.browser.navigate("https://jules.google.com")
            page.wait_for_timeout(5000)

            # 2. Click specific repository name
            try:
                page.click(f"text='{repo_name}'", timeout=5000)
                logging.info(f"Clicked repository: {repo_name}")
                page.wait_for_timeout(2000)
            except Exception as e:
                logging.warning(f"Could not click repository {repo_name}: {e}")

            # 3. Click 'x' to clear repository (clear context)
            try:
                page.click("button[aria-label='Clear repository']", timeout=5000)
                logging.info("Clicked 'X' to clear codebase.")
                page.wait_for_timeout(2000)
            except:
                logging.warning("Clear codebase button not found or already cleared.")

            # 4. Ensure "No Codebase" is selected
            try:
                page.click("text='No Codebase'", timeout=5000)
                logging.info("Selected 'No Codebase' mode.")
                page.wait_for_timeout(1000)
            except:
                pass

            # 5. Enter instructions
            try:
                 textarea = page.locator("textarea, div[contenteditable='true']").first
                 textarea.fill(f"Create a python script based on: {instructions}")
                 page.keyboard.press("Enter")
                 logging.info("Sent instructions to Jules chat.")
            except Exception as e:
                 logging.error(f"Failed to enter prompt in Jules: {e}")
                 return None

            # 6. Wait for response and handle long code
            # Wait dynamically for the generation instead of fixed timeout, up to 120s
            try:
                page.wait_for_selector("pre, code", timeout=120000)
            except Exception as e:
                logging.warning(f"Timeout waiting for code block to appear: {e}")

            # Check if there are code blocks
            code_blocks = page.locator("pre, code").count()
            if code_blocks > 0:
                 logging.info("Code generated by Jules. Proceeding to ask for file link...")
                 # Assuming we want to ask for a link anyway as per user instruction
                 textarea = page.locator("textarea, div[contenteditable='true']").first
                 textarea.fill("Kodenya terlalu panjang, bisakah berikan link file downloadnya?")
                 page.keyboard.press("Enter")
                 logging.info("Requested file download link from Jules.")

                 page.wait_for_timeout(10000)

                 # Wait for the link, click it, and download
                 try:
                     with page.expect_download(timeout=30000) as download_info:
                         # Click the download link generated by Jules
                         page.click("a:has-text('download'), a:has-text('.py')", timeout=15000)

                     download = download_info.value
                     code_path = "generated_script.py"
                     download.save_as(code_path)
                     logging.info(f"Downloaded code from Jules to {code_path}")
                     return code_path
                 except Exception as e:
                     logging.warning(f"Failed to download from link: {e}. Attempting to copy text instead.")

                     # Fallback: copy the first code block text
                     try:
                         code_text = page.locator("pre").first.inner_text()
                         code_path = "generated_script.py"
                         with open(code_path, "w") as f:
                             f.write(code_text)
                         logging.info(f"Copied code text directly to {code_path}")
                         return code_path
                     except Exception as ex:
                         logging.error(f"Failed to copy code text: {ex}")
                         return None
            else:
                 logging.warning("No code blocks found in Jules response.")
                 return None

        except Exception as e:
            logging.error(f"Critical error in JulesAgent: {e}")
            return None
